[project]
name = "nce-english-practices"
version = "0.1.0"
description = "English Tense Practice Web App"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.8.1",
    "python-dotenv>=1.2.1",
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
    "jinja2>=3.1.4",
    "readmdict>=0.1.1",
    "beautifulsoup4>=4.14.3",
    "python-lzo>=1.15",
    "google-genai>=1.53.0",
    "cryptography>=46.0.3",
]
